--- #YAML:1.0
name:                     CPAN-WWW-Testers
version:                  0.48
abstract:                 CPAN Testers Reports website generation code
author:
  - Barbie <barbie@cpan.org>
  - Leon Brocard <leon@astray.com>

license:                  perl
distribution_type:        module
installdirs:              site

requires:
  Archive::Extract:                 0
  Class::Accessor::Chained::Fast:   0
  Config::IniFiles:                 0
  CPAN::Testers::Common::DBUtils:   0.03
  CPAN::DistnameInfo:               0
  DateTime:                         0
  DBD::mysql:                       0
  DBD::SQLite:                      1.00
  File::Find::Rule:                 0
  File::Path:                       0
  File::Slurp:                      0.01
  FindBin:                          0
  Getopt::ArgvFile:                 0
  Getopt::Long:                     0
  Image::Imlib2:                    0
  IO::File:                         0
  JSON::Syck:                       0
  LWP::Simple:                      0.01
  Parse::CPAN::Authors:             0
  Path::Class:                      0
  OpenThought:                      0
  Sort::Versions:                   0
  Storable:                         0
  Template:                         2.08
  Template::Plugin::Comma:          0
  Template::Plugin::Cycle:          0
  XML::RSS:                         1.31
  YAML:                             0.01
recommends:
  Archive::Zip:                     0
  File::Copy:                       0
  File::Spec:                       0
  File::Basename:                   0
  Test::Differences:                0
  Test::More:                       0.70
  Test::Pod:                        1.00
  Test::Pod::Coverage:              0.08
  Test::CPAN::Meta:                 0.08
build_requires:
  Test::More:                       0.01

provides:
  CPAN::WWW::Testers:
    file:     lib/CPAN/WWW/Testers.pm
    version:  0.48
no_index:
  directory:
    - t
    - examples

resources:
  license:    http://dev.perl.org/licenses/
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=CPAN-WWW-Testers

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
