--- #YAML:1.0
name: CPAN-WWW-Testers
version: 0.33
author:
  - Leon Brocard <acme@astray.com>
abstract: Present CPAN Testers data
license: perl
generated_by: Module::Build version 0.2612, without YAML.pm
