--- #YAML:1.0
name: CPAN-WWW-Testers
version: 0.21
license: perl
distribution_type: module
requires:
  DBD::SQLite: 0.01
  DBI: 0.01
  File::Slurp: 0.01
  LWP::Simple: 0.01
  Template: 2.08
  Test::More: 0.01
  YAML: 0.01
  version: 0.01
recommends: {}
build_requires: {}
conflicts: {}
provides:
  CPAN::WWW::Testers:
    file: lib/CPAN/WWW/Testers.pm
    version: 0.21
generated_by: Module::Build version 0.19
