--- #YAML:1.0
name: CPAN-WWW-Testers
version: 0.25
author:
  - Leon Brocard <leon@astray.com>
abstract: Present CPAN Testers data
license: perl
requires:
  DBD::SQLite: 0.01
  DBI: 0.01
  File::Path: 0
  File::Slurp: 0.01
  Getopt::Long: 0
  LWP::Simple: 0.01
  Parse::BACKPAN::Packages: 0
  Storable: 0
  Template: 2.08
  Test::More: 0.01
  XML::RSS: 0.01
  YAML: 0.01
  version: 0.01
provides:
  CPAN::WWW::Testers:
    file: lib/CPAN/WWW/Testers.pm
    version: 0.25
generated_by: Module::Build version 0.2605
